# Generated by Django 2.2 on 2021-02-15 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210215_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skill_level',
        ),
    ]
